### ISSUE TITLE
代码漏提交

### ISSUE THREAD

**Issue by liwujun11111** [jinkg/Style#1]
现在代码编译不过 缺少local.properties

**Comment by jinkg** [comment]
这个文件里包含了keystore的相关信息，属于私密文件。你需要手动修改一下build.gradle来运行

**Comment by jinkg** [comment]
alias=
keyPassword=
storePassword=
keystorePath=

buglyAppId=
flurryApiKey=
里面一共有这些字段，你也可选择自己去创建。或者修改相应代码。使这些字段无效。

在presentation的build.gradle文件中，有这些代码
Properties properties = new Properties()
properties.load(project.rootProject.file('local.properties').newDataInputStream())

def alias = properties.get('alias')
def _keyPassword = properties.get('keyPassword')
def _storePassword = properties.get('storePassword')
def keystorePath = properties.get('keystorePath')
def buglyAppId = properties.get('buglyAppId')
def flurryApiKey = properties.get('flurryApiKey')

使从local.properties里面读取配置。你可以对它进行修改。

**Comment by liwujun11111** [comment]
哥们 好像还是编译不过啊 使用命令编译如下
![image](https://user-images.githubusercontent.com/7313292/29062323-d015a106-7c53-11e7-89fe-a5b5640f356d.png)  直接同步代码 
![image](https://user-images.githubusercontent.com/7313292/29062349-ea441f58-7c53-11e7-872c-aebbabb63eee.png)

**Comment by liwujun11111** [comment]
![image](https://user-images.githubusercontent.com/7313292/29062434-46bdcba8-7c54-11e7-8e0a-4a4bcdf5f1c4.png)

**Comment by jinkg** [comment]
第一步，修改presentation的build.gradle如下：
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-android-extensions'

//Properties properties = new Properties()
//properties.load(project.rootProject.file('local.properties').newDataInputStream())
//
//def alias = properties.get('alias')
//def _keyPassword = properties.get('keyPassword')
//def _storePassword = properties.get('storePassword')
//def keystorePath = properties.get('keystorePath')
//def buglyAppId = properties.get('buglyAppId')
//def flurryApiKey = properties.get('flurryApiKey')

def CHANNEL = System.getProperty("channel", "default")
def APP_NAME = System.getProperty("app_name", "Style")

android {
    compileSdkVersion COMPILE_SDK_VERSION as int
    buildToolsVersion BUILD_TOOLS_VERSION as String
    defaultConfig {
        applicationId "com.yalin.style"
        minSdkVersion MIN_SDK_VERSION as int
        targetSdkVersion TARGET_SDK_VERSION as int
        versionCode APP_VERSION_CODE as int
        versionName APP_VERSION_NAME as String

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

//        buildConfigField("String", "BUGLY_APP_ID", "\"${buglyAppId}\"")
//        buildConfigField("String", "FLURRY_API_KEY", "\"${flurryApiKey}\"")

        resValue("string", "app_name_ext", "${APP_NAME}")
    }
//    signingConfigs {
//        release {
//            keyAlias alias
//            keyPassword _keyPassword
//            storeFile file(keystorePath)
//            storePassword _storePassword
//        }
//    }
    buildTypes {
        debug {
            minifyEnabled false
//            signingConfig signingConfigs.release
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'),
                    'proguard-rules.pro', 'component-proguard.pro'

//            signingConfig signingConfigs.release
        }
    }
    productFlavors {
        demo {
            buildConfigField("boolean", "DEMO_MODE", "true")
        }
        production {
            buildConfigField("boolean", "DEMO_MODE", "false")
        }
        googleprod {
            buildConfigField("boolean", "DEMO_MODE", "false")
        }
    }

}

dependencies {
    compile "com.android.support:appcompat-v7:${SUPPORT_LIBRARY_VERSION}"
    compile "com.android.support:exifinterface:${SUPPORT_LIBRARY_VERSION}"
    compile "com.android.support:design:${SUPPORT_LIBRARY_VERSION}"
    compile "com.android.support:recyclerview-v7:${SUPPORT_LIBRARY_VERSION}"
    compile "com.android.support:percent:${SUPPORT_LIBRARY_VERSION}"

    compile "com.google.code.gson:gson:${GSON_VERSION}"
    compile "com.squareup.okhttp3:okhttp:${OK_HTTP_VERSION}"
    compile "com.google.dagger:dagger:${DAGGER_VERSION}"
    compile "io.reactivex.rxjava2:rxjava:${RXJAVA_VERSION}"
    compile "io.reactivex.rxjava2:rxandroid:${RXANDROID_VERSION}"
    compile "com.github.bumptech.glide:glide:${GLIDE_VERSION}"
    compile "org.greenrobot:eventbus:${EVENT_BUS_VERSION}"
    compile "com.tencent.bugly:crashreport:${BUGLY_VERSION}"
    compile "com.flurry.android:analytics:${FLURRY_VERSION}"

    googleprodCompile "com.google.firebase:firebase-core:${FIRE_BASE_VERSION}"
    // Only use crash reporting in the "prod" product flavor
    googleprodCompile "com.google.firebase:firebase-crash:${FIRE_BASE_VERSION}"

//    annotationProcessor "com.google.dagger:dagger-compiler:${DAGGER_VERSION}"
    kapt "com.google.dagger:dagger-compiler:${DAGGER_VERSION}"

    compile 'com.afollestad.material-dialogs:core:0.9.4.5'

    compile project(':domain')
    compile project(':engine')
    demoCompile project(path: ':data', configuration: 'demoDebug')
    productionCompile project(path: ':data', configuration: 'productionRelease')
    googleprodCompile project(path: ':data', configuration: 'productionRelease')

    demoCompile 'com.facebook.stetho:stetho:1.5.0'

    testCompile 'junit:junit:4.12'
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
}

project.afterEvaluate {
    android.applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def oldFile = output.outputFile

            output.outputFile = new File(oldFile.parent,
                    "${APP_NAME}-${CHANNEL}.apk")
        }
    }
}

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-android-extensions:${KOTLIN_VERSION}"
    }
}
apply plugin: 'com.google.gms.google-services'

第二步，注释掉StyleApplication中的Bugly相关代码：
//        CrashReport.initCrashReport(applicationContext,
//                BuildConfig.BUGLY_APP_ID, LogUtil.LOG_ENABLE)
//        CrashReport.setAppChannel(applicationContext, com.yalin.style.data.BuildConfig.CHANNEL)

第三步，到demo渠道下面找到Analytics类，注释掉FlurryAgent相关代码。（如果打其他渠道包，也需要到其他渠道下去注释掉）
   override fun init(context: Context) {
//        FlurryAgent.Builder().withLogEnabled(LogUtil.LOG_ENABLE)
//                .build(context, BuildConfig.FLURRY_API_KEY)
    }

第四步，使用命令./gradlew assembleDemoDebug打包。第一次可能会打包不通过，在执行一次这个命令（还不清楚是什么原因，估计是dagger2的kotlin版本问题）

**Comment by jinkg** [comment]
还有另外一个问题，由于你打的包的签名文件不同，服务端不会返回数据给你。

你可以下载新Release包看效果。[2.7.0](https://github.com/jinkg/Style/releases)

**Comment by liwujun11111** [comment]
没有 我这边主要是NDK环境出问题了 现在解决了多谢
