### ISSUE TITLE
Unable to resolve dependancy

### ISSUE THREAD

**Issue by rahul107** [jinkg/Style#2]
Hello,
i am new in android and i download your project but it seems some errors which i can't solve,
i upload the image of that errors please  help me to solve that errors
thanks

![error](https://user-images.githubusercontent.com/26810084/34285272-879cf634-e6fe-11e7-81e4-528c3e1cac88.png)

**Comment by jinkg** [comment]
What's the detail info content?

You can update your Android Studio to the least updated version, and retry.
